### ISSUE TITLE
Typos: use "accept" instead of "accpet"

### ISSUE THREAD

**Issue by Aden-Q** [xiaolincoder/CS-Base#105]
A lot of occurrence of "accpet" (I found them mainly in 4.1 network-tcp, at least 11 places, but haven't check other places).

"accpet" is a typo for "accept".

**Comment by mrxiaojie** [comment]
中午好！您的邮件我已经收到了，谢谢您的支持！

**Comment by youzi-2333** [comment]
Hello @Aden-Q ,

911d7c7 has already solved this problem. Currently, there is no "accpet" in `tcp_no_accpet.md`, but the filename can't be changed.
(I remembered editing this file and fixing this, but I cannot find my commit in this repo)
Therefore, this issue can be closed. Thank you for your feedback!
