### ISSUE TITLE
提问：关于幻读

### ISSUE THREAD

**Issue by RuoCJ** [xiaolincoder/CS-Base#113]
![image](https://user-images.githubusercontent.com/53935240/234452953-f39c9451-3f82-4c40-9b2c-1a468838cf50.png)
关于幻读，有一些疑问：
我看文中说，当同一个查询在不同的时间产生不同的结果集时，事务中就会出现所谓的幻象问题。例如，如果 SELECT 执行了两次，但第二次返回了第一次没有返回的行，则该行是“幻像”行。
但是按照正常的逻辑来说，这样是说不通的。
比如A第一次查询，查出5条记录，B在A之后，插入一条数据，然后A再次查询，难道B插入的那一条记录不应该被查出来吗？感觉有些逻辑不通啊。

**Comment by xyohn** [comment]
如果你说的A和B是两次不同的事务，且只讨论读事务的话
1. 在RC或更低的级别上，B提交了事务的情况下，A再次查询确实会查出这条数据，但这种情况也算是幻读
2. 在RR级别上，无论B是否提交了事务，A都查不出来这条数据，因为RR级别下能规避一定条件下的读幻读

至于你说的按照正常逻辑，这个用词是用点奇怪的，从事务ACID特性的I来说，就是强调不同事务并发执行期间尽可能的互不影响；越严苛的隔离级别，事务并发执行之间的影响也会越小

不知道能否解答你的疑问

**Comment by RuoCJ** [comment]
这是我在别的地方看到的答案，我觉得这个更能解释什么是幻读：select 某记录是否存在，不存在，准备插入此记录，但执行 insert 时发现此记录已存在，无法插入，此时就发生了幻读

**Comment by xyohn** [comment]
> 这是我在别的地方看到的答案，我觉得这个更能解释什么是幻读：select 某记录是否存在，不存在，准备插入此记录，但执行 insert 时发现此记录已存在，无法插入，此时就发生了幻读

这是读写幻读 这个在 RR 下无法避免
读读幻读在 RR 下是可以避免的

**Comment by RuoCJ** [comment]
> > 这是我在别的地方看到的答案，我觉得这个更能解释什么是幻读：select 某记录是否存在，不存在，准备插入此记录，但执行 insert 时发现此记录已存在，无法插入，此时就发生了幻读
> 
> 这是读写幻读 这个在 RR 下无法避免 读读幻读在 RR 下是可以避免的

谢谢你
