### ISSUE TITLE
提问：关于间隙锁和插入意向锁

### ISSUE THREAD

**Issue by Choconut233** [xiaolincoder/CS-Base#114]
> 插入意向锁与间隙锁的另一个非常重要的差别是：尽管「插入意向锁」也属于间隙锁，但两个事务却不能在同一时间内，一个拥有间隙锁，另一个拥有该间隙区间内的插入意向锁（当然，插入意向锁如果不在间隙锁区间内则是可以的）。

这里没懂，插入意向锁本来不就是在等待别的事务的间隙锁释放的时候形成的吗？为什么这里又说一个事务加了间隙锁另一个事务不可以在这个间隙加插入意向锁，那插入意向锁的意义是什么？

**Comment by Choconut233** [comment]
在后面找到了答案
> MySQL 加锁时，是先生成锁结构，然后设置锁的状态，如果锁状态是等待状态，并不是意味着事务成功获取到了锁，只有当锁状态为正常状态时，才代表事务成功获取到了锁
所以这里的插入意向锁只是等待状态，还没有获取到

**Comment by xiaolincoder** [comment]
是的， 等待状态并不意味着获取到，要看锁的状态
