### ISSUE TITLE
图解redis错别字勘误

### ISSUE THREAD

**Issue by 357447923** [xiaolincoder/CS-Base#128]
[https://www.xiaolincoding.com/redis/cluster/sentinel.html#%E5%93%A8%E5%85%B5%E9%9B%86%E7%BE%A4%E6%98%AF%E5%A6%82%E4%BD%95%E7%BB%84%E6%88%90%E7%9A%84](url)
在总结之前，“正式通过 Redis 的发布者/订阅者机制，哨兵之间可以相互感知，然后组成集群，同时，哨兵又通过 INFO 命令，在主节点里获得了所有从节点连接信息，于是就能和从节点建立连接，并进行监控了。”中"正式"有误，应为"正是"。
谢谢大佬能够提供像这样完善且易懂的内容。

**Comment by zhuhh666** [comment]
可以提PR
