### ISSUE TITLE
左边的目录希望能有按钮隐藏起来

### ISSUE THREAD

**Issue by zitongchen** [xiaolincoder/CS-Base#13]
要是能做个按钮将左边的目录隐藏起来就更好了，在使用 ipad 阅读的时候左边的目录栏占据了一定的空间，导致无法全屏阅读文章的内容。
![image](https://user-images.githubusercontent.com/12184118/168197340-d4639f38-c2cc-4dc8-a79f-9d82a75a97af.png)

**Comment by xiaolincoder** [comment]
现在网站已支持隐藏左侧拦
