### ISSUE TITLE
MySQL 记录锁+间隙锁可以防止删除操作而导致的幻读吗

### ISSUE THREAD

**Issue by wgkflyit** [xiaolincoder/CS-Base#141]
针对当前读,并不能避免幻读,考虑如下情况:
事务A:
begin
 a: select * from test where id >5 for update 
x: select * from test where id >5 for update
commit
事务B
begin:
 c : insert into test (ID) values(6)
commit
事务A先执行到a处, 事务B开启后执行,是可以正常insert 和提交的. 提交完成事务A执行到x处,会出现幻读

**Comment by mrxiaojie** [comment]
晚上好！您的邮件我已经收到了，谢谢您的支持！

**Comment by xiaolincoder** [comment]
你事务 a 都提交了，事务 a 的 for update 的锁都释放了，自然事务 b 可以成功插入。如果你事务 a 没提交，事务 b 去插入，是会阻塞的（可重复读隔离级别下）。
