### ISSUE TITLE
HTTP /2 队头阻塞问题

### ISSUE THREAD

**Issue by ZonzeeLi** [xiaolincoder/CS-Base#15]
小林，有一个问题想请您解答一下。我看您写的资料，HTTP /2 的队头阻塞发生在TCP层传输的多个包，其中某一个包如果丢失了，那么后面的字节数据存放在内核缓冲区中，只有该数据包的数据到达，才能从内核中拿到数据。我想问，假设多条请求stream1、2、3同时到达，stream2的某个数据包丢失了，stream2因为后续数据包存放在缓冲区，或超时重传等操作等待，**但是这个会影响stream1、3的响应么**，我的问题是，**因为流式传输、多路复用，服务器并不需要按照顺序去处理请求，但是如果sream2阻塞了，会影响后续请求的处理么**。如果会影响的话，这个和 HTTP /1.1的区别是HTTP /1.1的队头阻塞是因为响应必须按照请求的顺序做出回应，如果某一个请求的没收到响应，后续都会阻塞，而HTTP /2 没有顺序这一概念，这是我阅读完后的理解，请麻烦看下是否正确。而且我理解了下您文章部分的内容，我描述下个人理解的HTTP /2这部分内容，由于不同的 Stream 的帧可以是乱序发送的，所以在服务器的内核缓冲区部分，**数据包的顺序可能不是按照同一个请求的顺序发送过来的**，这句话正确么，**假设stream1、2发送过来，内核缓冲区接收到的情况可能是，stream2的数据包1、stream1的数据包1，stream2的数据包2、stream2的数据包3、stream1的数据包2...这种情况，由于每个帧都有Stream Id信息，所以在发送完后会有序组装，这样子如果stream2的数据包丢失了，后面的数据包都会在内核缓冲区等待，所以stream1的数据包尽管接收完毕，也没办法读取完整，所以也阻塞了**，也请麻烦看下我这么理解是否正确。

**Comment by xiaolincoder** [comment]
1. stream1、2、3同时到达，stream2的某个数据包丢失，会不会影响stream1、3的响应？主要看 stream1和 stream 3 的tcp数据报的 seq 是不是比 stream2的tcp数据报  seq 大还是小，如果比它小，那么就不会影响 stream1、3的响应，如果比它大，那么就会放在内核缓冲区，应用程序无法读到stream1、3的请求，自然就无法对stream1、3做出响应。
2. 数据包的顺序可能不是按照同一个请求的顺序发送过来的 ---- 这个正确

**Comment by ZonzeeLi** [comment]
感谢 清楚了很多。
