### ISSUE TITLE
「network/1_base/tcp_ip_model」网络层主机号计算方法

### ISSUE THREAD

**Issue by RavenLite** [xiaolincoder/CS-Base#17]
[原文](https://github.com/xiaolincoder/CS-Base/blob/main/network/1_base/tcp_ip_model.md#%E7%BD%91%E7%BB%9C%E5%B1%82)给出的方法是“将 10.100.122.2 和 255.255.255.0 进行按位与运算，就可以得到网络号和主机号”
配图中显示主机号是“00000000”
但实际上主机号的计算方法应该是将子网掩码取反后与IP地址进行按位与运算
正确的主机号应该是“00000010”

**Comment by xiaolincoder** [comment]
已修正到网站：[2.1 TCP/IP 网络模型有哪几层？](https://xiaolincoding.com/network/1_base/tcp_ip_model.html)
