### ISSUE TITLE
網站缺黑暗模式

### ISSUE THREAD

**Issue by tommy1680** [xiaolincoder/CS-Base#2]
小林您好
您的圖解系列pdf都有黑暗模式
網站怎麼缺切換為黑暗模式的功能呢？
麻煩您有空時添上，感恩

您的圖解網路讓我受益良多，感謝

**Comment by XmeteoriteX** [comment]
推荐浏览器插件 Dark Reader

**Comment by xiaolincoder** [comment]
@XmeteoriteX  感谢推荐，我试了下效果不错

**Comment by jwcen** [comment]
> 

手机端没有

**Comment by xiaolincoder** [comment]
现在网站已支持黑夜模式切换
