### ISSUE TITLE
错别字 - 数据库 - 事务的隔离级别

### ISSUE THREAD

**Issue by lizhendong128** [xiaolincoder/CS-Base#20]
数据库 - [事务的隔离级别](https://xiaolincoding.com/mysql/transaction/mvcc.html#%E4%BA%8B%E5%8A%A1%E7%9A%84%E9%9A%94%E7%A6%BB%E7%BA%A7%E5%88%AB%E6%9C%89%E5%93%AA%E4%BA%9B)这篇文章，有张图片里面用词不是很准确，read view翻译成了视图，容易和数据库的视图相混淆，其他图片和文字都没有视图二字。
![image](https://user-images.githubusercontent.com/24618122/174730981-8de17e33-2a5e-4a96-9da7-bbee12d69455.png)

以及这张图片下面的文字也有排版的问题~
![image](https://user-images.githubusercontent.com/24618122/174731294-e179477d-3d65-4de6-9ab4-c76cca987142.png)
希望修改一下，谢谢~~

**Comment by lizhendong128** [comment]
提一个很小的建议，还是这篇文章，有一张图可以多添加一些元素，更容易理解
![image](https://user-images.githubusercontent.com/24618122/174733803-0a1ec7c7-d486-4828-a1de-35a60c1530f8.png)

**Comment by xiaolincoder** [comment]
网站内容已更正
