### ISSUE TITLE
[勘误]mysql基础篇 - 执行一条 select 语句，期间发生了什么？

### ISSUE THREAD

**Issue by Issac-v** [xiaolincoder/CS-Base#21]
文章网址: [执行一条 select 语句，期间发生了什么？](https://xiaolincoding.com/mysql/base/how_select.html#%E8%A7%A3%E6%9E%90%E5%99%A8)
具体错误: SQL语法树的构建应该是语法分析阶段的任务, 文中错把其归类到词法分析下

**Comment by hcldadi** [comment]
我这也补充一个疑问，文中提到Mysql 8.0把查询缓存去掉了，但我看官方内存模型里还是有个buffer pool，也是缓存查询用的，这个是不是有误？https://dev.mysql.com/doc/refman/8.0/en/innodb-buffer-pool.html

**Comment by xiaolincoder** [comment]
@hcldadi 这里说的查询缓存是 server 层的，也就是 MySQL 8.0 版本移除的是 server 层的查询缓存，并不是 Innodb 存储引擎中的 buffer poll。
