### ISSUE TITLE
 错别字：图解系统 9.2 I/O多路复用

### ISSUE THREAD

**Issue by JokerChenX** [xiaolincoder/CS-Base#31]
原文：
那么，我们可以使用线程池的方式来避免线程的频繁创建和销毁，所谓的线程池，就是提前创建若干个线程，这样当由新连接建立时，将这个已连接的 Socket 放入到一个队列里，然后线程池里的线程负责从队列中取出已连接 Socket 进程处理。

错别字：
"已连接 Socket 进程处理" 中的"进程"应该修改为"进行"

**Comment by xiaolincoder** [comment]
已修正
