### ISSUE TITLE
部分图片加载失败

### ISSUE THREAD

**Issue by ltnil** [xiaolincoder/CS-Base#4]
![image-20220318201205725](/Users/xiaolin/Library/Application Support/typora-user-images/image-20220318201205725.png)
部分文章中图片如上所示，加载失败，readme中是否可以使用相对位置~~

**Comment by xiaolincoder** [comment]
这是哪篇文章的？我没找到

**Comment by xiaolincoder** [comment]
@ltnil  这是哪篇文章的？我没找到

**Comment by ltnil** [comment]
<img width="588" alt="图片" src="https://user-images.githubusercontent.com/20036221/159856135-2b9c3c90-fc80-4480-aea8-b9a27e2ef3c8.png">
你全局搜索一下关键字/User开头的，存储的都是你电脑上的路径

**Comment by ltnil** [comment]
<img width="533" alt="图片" src="https://user-images.githubusercontent.com/20036221/159856331-5d3f4e65-22a4-444a-96f3-5be1e977052a.png">
这些路径能不能换成相对路径，绝对路径在本地不太好用(./xx/xxx/xxx)

**Comment by xiaolincoder** [comment]
@ltnil 你两个md是我本地临时写的文章，并不是图解里的内容，你可以删掉。然后这路径我没办法改，因为网站的导航规定是这样用的

**Comment by ltnil** [comment]
好的，谢谢
