### ISSUE TITLE
【页面错误】发现一个页面表述错误

### ISSUE THREAD

**Issue by xlcodes** [xiaolincoder/CS-Base#42]
在作者大大的【图解系统介绍】篇的【要怎么阅读】中，“所以肯定是没有教科书那么细致和全面，当然也不就不会有很多废话，都是直击重点，不绕弯，而且有的知识点书上看不到”，完整的表述是否应该是“所以肯定是没有教科书那么细致和全面，当然也就不会有很多废话，都是直击重点，不绕弯，而且有的知识点书上看不到”？当然也有可能是我理解错了。

**Comment by xiaolincoder** [comment]
已修正
