### ISSUE TITLE
[疑问]Mysql中可重复读隔离级别Read View生成时机

### ISSUE THREAD

**Issue by jiupie** [xiaolincoder/CS-Base#43]
原文1：[事务隔离级别是怎么实现的？](https://xiaolincoding.com/mysql/transaction/mvcc.html#%E5%8F%AF%E9%87%8D%E5%A4%8D%E8%AF%BB%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84)
文中“可重复读隔离级别是启动事务时生成一个 Read View，然后整个事务期间都在用这个 Read View。”

原文2：在[MySQL 可重复读隔离级别，完全解决幻读了吗？](https://xiaolincoding.com/mysql/transaction/phantom.html#%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8F%91%E7%94%9F%E5%B9%BB%E8%AF%BB%E7%8E%B0%E8%B1%A1%E7%9A%84%E5%9C%BA%E6%99%AF)
文中“在可重复读隔离级别下，事务 A 第一次执行普通的 select 语句时生成了一个 ReadView，之后事务 B 向表中新插入了一条 id = 5 的记录并提交。”

个人看法：
原文1和原文2的描述有冲突，
**可重复读隔离级别Read View生成时机不是在事务启动后第一次执行普通的 select 语句时才生成的 Read View吗？**

**Comment by xiaolincoder** [comment]
在 MySQL 有两种开启事务的命令，分别是：

- 第一种：begin/start transaction 命令；
- 第二种：start transaction with consistent snapshot 命令；

这两种开启事务的命令，事务的启动时机是不同的：

- 执行了 begin/start transaction 命令后，并不代表事务启动了。只有在执行这个命令后，执行了selete 语句后， 才会创建一个 Read View
- 执行了 start transaction with consistent snapshot 命令，就会马上启动事务，然后创建一个 Read View

[事务隔离级别是怎么实现的？](https://xiaolincoding.com/mysql/transaction/mvcc.html#%E5%8F%AF%E9%87%8D%E5%A4%8D%E8%AF%BB%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84)文章的案例都是基于start transaction with consistent snapshot ，即启动了事务后，就创建Read View。

[MySQL 可重复读隔离级别，完全解决幻读了吗？](https://xiaolincoding.com/mysql/transaction/phantom.html#%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8F%91%E7%94%9F%E5%B9%BB%E8%AF%BB%E7%8E%B0%E8%B1%A1%E7%9A%84%E5%9C%BA%E6%99%AF)这篇文章的案例是基于begin，即只是开启事务，执行完select后，才会创建Read View

**Comment by jiupie** [comment]
谢谢，现在明白了
