### ISSUE TITLE
圖解操作系統 - a = 1 + 2 执行具体过程 

### ISSUE THREAD

**Issue by HiHiBrian** [xiaolincoder/CS-Base#48]
Hi 作者你好,

在 [a = 1 + 2 執行具體過程](https://xiaolincoding.com/os/1_hardware/how_cpu_run.html#a-1-2-%E6%89%A7%E8%A1%8C%E5%85%B7%E4%BD%93%E8%BF%87%E7%A8%8B) 這個章節, 有提到說數據與指令是放於不同的記憶體區間, 認知中程式碼應該是位於記憶體中的 text section, 而 text section 應該相對於其他區間是位在比較低記憶體的位置!?
因此文中提到的正文段 (text section) 是否其記憶體位置應該要比數據段還低呢?
若觀念有誤, 還請見諒!

**Comment by xiaolincoder** [comment]
是的，你理解没错，数据段的地址比正文段的地址高。文章已经修正。
