### ISSUE TITLE
提问，

### ISSUE THREAD

**Issue by chris3will** [xiaolincoder/CS-Base#72]
Redis集群
集群脑裂导致数据丢失怎么办
解决方案：
"当主节点发现从节点下线或者通信超时的总数量小于阈值时，那么禁止主节点进行写数据，直接把错误返回给客户端。"

里面的小于是不是应该改为“大于”？

**Comment by xiaolincoder** [comment]
github的md文件，我忘记改了，网站的文章很早之前纠正过程。

“当主节点发现「从节点下线的数量太多」，或者「网络延迟太大」的时候，那么主节点会禁止写操作，直接把错误返回给客户端。”
