### ISSUE TITLE
提问tcp

### ISSUE THREAD

**Issue by James987** [xiaolincoder/CS-Base#80]
您好，对于tcp三次握手，第三次握手client发出ack，紧接着发出数据包，并且数据包先于ack到达server，这个情景下会发生什么

**Comment by Hxhao2000** [comment]
我的理解是，数据包的flag中会带有ack，所以是正常的，你可以把这种情况看作是第三次握手直接带上数据的情况。

**Comment by James987** [comment]
> 我的理解是，数据包的flag中会带有ack，所以是正常的，你可以把这种情况看作是第三次握手直接带上数据的情况。

谢谢

**Comment by dandyhuang** [comment]
> 对于tcp三次握手，第三次握手client发出ack，紧接着发出数据包，并且数据包先于ack到达server，这个情景下会发生什么

直接回丢弃这个包，因为服务端回校验ack包的。收到非法的包，会在直接发送 RST 报文给客户端

**Comment by xiaolincoder** [comment]
数据包带有的 ack 值和第三次握手的 ack 是一样的，此时会建立连接，并完成数据接收。
