### ISSUE TITLE
图解系统-3.1 Linux内核 VS Windows内核-错别字勘误

### ISSUE THREAD

**Issue by charfole** [xiaolincoder/CS-Base#83]
https://xiaolincoding.com/os/2_os_structure/linux_vs_windows.html#elf
“不过，Linux 也实现了动态加载内核模块的功能，例如大部分设备驱动是以可加载模块的形式存在的，与内核其他模块**解藕**，让驱动开发和驱动加载更为方便、灵活。”
解藕-->解耦。

**Comment by SnowWarri0r** [comment]
#84
